# Generated by Django 2.2.3 on 2019-07-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0002_category_cennostatus_disignation_district_gender_level_ownership_region_regstatus_school_schtype_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='acc_type',
            new_name='sec_type',
        ),
    ]
