# Generated by Django 2.2.3 on 2019-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0003_auto_20190722_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='default.png', upload_to='school_logos'),
        ),
    ]
