# Generated by Django 2.2.3 on 2019-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0004_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='school_logos'),
        ),
    ]
