# Generated by Django 2.2.3 on 2019-07-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0005_auto_20190723_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='default.png', upload_to='school_logos'),
        ),
    ]
