# Generated by Django 2.2.3 on 2019-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0006_auto_20190723_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='gender_type',
            new_name='gender',
        ),
    ]
