# Generated by Django 2.2.3 on 2019-07-26 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0011_auto_20190724_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='teacher_photos'),
        ),
        migrations.CreateModel(
            name='TransferTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_valid', models.DateField(blank=True, null=True)),
                ('date_transfered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('disignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Disignation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_home.School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_home.Teacher')),
            ],
        ),
    ]
