# Generated by Django 2.2.3 on 2019-07-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0013_transferteacher_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disignation',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='dis_type',
            new_name='des_type',
        ),
        migrations.RemoveField(
            model_name='transferteacher',
            name='disignation',
        ),
        migrations.AddField(
            model_name='transferteacher',
            name='designation',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='school_home.Designation'),
        ),
    ]
