# Generated by Django 2.2.3 on 2019-07-28 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0014_auto_20190726_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_source', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='access',
            name='acc_type',
            field=models.CharField(max_length=45, verbose_name='Access Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(max_length=45, verbose_name='Category Type'),
        ),
        migrations.AlterField(
            model_name='cennostatus',
            name='cns',
            field=models.CharField(max_length=45, verbose_name='Center No. Registration status'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='des_type',
            field=models.CharField(max_length=45, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='district',
            name='dis_name',
            field=models.CharField(max_length=45, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_home.School'),
        ),
        migrations.AlterField(
            model_name='facstatus',
            name='facility_status',
            field=models.CharField(max_length=45, verbose_name='Facility status'),
        ),
        migrations.AlterField(
            model_name='factype',
            name='facility_type',
            field=models.CharField(max_length=45, verbose_name='Facility Type'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=45, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='level',
            name='lev_name',
            field=models.CharField(max_length=45, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='own_type',
            field=models.CharField(max_length=45, verbose_name='Ownership Type'),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_name',
            field=models.CharField(max_length=45, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='regstatus',
            name='rs_type',
            field=models.CharField(max_length=45, verbose_name='Registration status'),
        ),
        migrations.AlterField(
            model_name='school',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Access', verbose_name='School Access'),
        ),
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Category', verbose_name='School Category'),
        ),
        migrations.AlterField(
            model_name='school',
            name='cen_no',
            field=models.CharField(max_length=100, verbose_name='Center Number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='cennostatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Cennostatus', verbose_name='Center No. Registration status'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Level', verbose_name='Hieghest Level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='motto',
            field=models.CharField(max_length=100, verbose_name='School Motto'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Ownership', verbose_name='Ownership'),
        ),
        migrations.AlterField(
            model_name='school',
            name='reg_no',
            field=models.CharField(max_length=100, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='regstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Regstatus', verbose_name='Registration status'),
        ),
        migrations.AlterField(
            model_name='school',
            name='schtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Schtype', verbose_name='School Type'),
        ),
        migrations.AlterField(
            model_name='school',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.Section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='school',
            name='yr_cnr',
            field=models.DateField(blank=True, null=True, verbose_name='Year of Center No. Registration'),
        ),
        migrations.AlterField(
            model_name='school',
            name='yr_est',
            field=models.DateField(verbose_name='Year Established'),
        ),
        migrations.AlterField(
            model_name='school',
            name='yr_reg',
            field=models.DateField(blank=True, null=True, verbose_name='Year of Registration'),
        ),
        migrations.AlterField(
            model_name='schtype',
            name='sch_type',
            field=models.CharField(max_length=45, verbose_name='School Type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_type',
            field=models.CharField(max_length=45, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Teacher's Name"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='reg_no',
            field=models.CharField(max_length=200, verbose_name='Registration Status'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='school_home.TeacherStatus', verbose_name='Teacher Status'),
        ),
        migrations.AlterField(
            model_name='transferteacher',
            name='date_valid',
            field=models.DateField(blank=True, null=True, verbose_name='Transfer Teacher Until'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('year', models.DateField(default=django.utils.timezone.now)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_home.ResourceType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_home.ResourceSource')),
            ],
        ),
    ]
