# Generated by Django 2.2.3 on 2019-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_home', '0018_auto_20190728_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='teacher_photos'),
        ),
    ]
